version: '3.8'
services:
  redis-cache:
    image: redis/redis-stack:latest
    container_name: voter_cache
    restart: always
    ports: 
      - 6379:6379   # Redis service
      - 8001:8001   # Redis Commander
    # networks:
    #   - backend
  voter-api:
    image: voter-api:latest
    container_name: voter-api
    restart: always
    ports: 
      - 8080:8080
    # networks:
    #   - backend
    #   - frontend
    depends_on:
      - redis-cache
    environment:
      - REDIS_URL=redis-cache:6379
# networks:
#   frontend:
#     internal: false
#   backend:
#     internal: true
